### ISSUE TITLE
gocloud?

### ISSUE THREAD

**Issue by nodesocket** [gliderlabs/hostctl#1]
Looks nice, like **fog** and **libcloud** in go. Have you seen https://github.com/dynport/gocloud? Thoughts?

**Comment by progrium** [comment]
Are you comparing hostctl to gocloud?

**Comment by nodesocket** [comment]
No comparison at all, just curious the rationale for writing hostctl. Do you feel there are weaknesses in gocloud?

**Comment by progrium** [comment]
It's not entirely ready for public consumption, but I explained in the livecoding.tv stream. The point was to not be a universal tool for cloud providers, but a very focused and well designed tool to make it easy to:
- create hosts
- destroy hosts
- list hosts
- get host ips

No attempt to be a library. No attempt to have Everything You Need For Cloud. Just making it easy to run and manage one-off cloud VMs from the shell. Anything more serious would lead to Terraform.

**Comment by nodesocket** [comment]
Gottcha. Thanks.
